
# Generated by Qodo Gen

# Dependencies:
# pip install pytest-mock
import pytest

from src.agents.ticket_agent import TicketAgent
from src.customers.service import CustomerService
from src.models.common import ObjectIdField
from src.tickets.models import Ticket, TicketCategory, TicketSchema
from src.tickets.service import TicketService


class TestTicketAgent:
    # Agent successfully creates a new ticket with valid customer ID and content
    @pytest.mark.asyncio
    async def test_create_ticket_success(self, mocker):
        # Arrange
        ticket_service = mocker.Mock(spec=TicketService)
        customer_service = mocker.Mock(spec=CustomerService)
        agent = TicketAgent(ticket_service, customer_service)

        test_ticket = Ticket(
            customer_id=ObjectIdField("507f1f77bcf86cd799439011"),
            subject="Test ticket",
            description="Test description"
        )
        expected_ticket = TicketSchema(id=ObjectIdField("507f1f77bcf86cd799439012"), **test_ticket.model_dump())
        ticket_service.create.return_value = expected_ticket

        # Act
        result = await agent._tool_create_ticket(test_ticket)

        # Assert
        assert result == expected_ticket
        ticket_service.create.assert_called_once_with(test_ticket)

    # Agent correctly analyzes ticket and assigns appropriate category from predefined options
    @pytest.mark.asyncio
    async def test_analyze_ticket_category_assignment(self, mocker):
        # Arrange
        ticket_service = mocker.Mock(spec=TicketService)
        customer_service = mocker.Mock(spec=CustomerService)
        agent = TicketAgent(ticket_service, customer_service)

        test_ticket = TicketSchema(
            id=ObjectIdField("507f1f77bcf86cd799439011"),
            customer_id=ObjectIdField("507f1f77bcf86cd799439012"),
            subject="Billing Issue",
            description="Payment failed"
        )
        ticket_service.find_one.return_value = test_ticket

        mocker.patch.object(agent, '_suggest_category', return_value=TicketCategory.BILLING.value)
        mocker.patch.object(agent, '_suggest_priority', return_value="high")

        # Act
        result = await agent._tool_analyze_ticket(ObjectIdField("507f1f77bcf86cd799439011"))

        # Assert
        ticket_service.update_ticket_analysis.assert_called_once_with(
            ObjectIdField("507f1f77bcf86cd799439011"),
            category=TicketCategory.BILLING.value,
            priority="high"
        )

    # Handle empty or malformed ticket descriptions
    @pytest.mark.asyncio
    async def test_analyze_ticket_empty_description(self, mocker):
        # Arrange
        ticket_service = mocker.Mock(spec=TicketService)
        customer_service = mocker.Mock(spec=CustomerService)
        agent = TicketAgent(ticket_service, customer_service)

        test_ticket = TicketSchema(
            id=ObjectIdField("507f1f77bcf86cd799439011"),
            customer_id=ObjectIdField("507f1f77bcf86cd799439012"),
            subject="General Question",
            description=None
        )
        ticket_service.find_one.return_value = test_ticket

        mocker.patch.object(agent, '_suggest_category', return_value=TicketCategory.GENERAL.value)
        mocker.patch.object(agent, '_suggest_priority', return_value="low")

        # Act
        result = await agent._tool_analyze_ticket(ObjectIdField("507f1f77bcf86cd799439011"))

        # Assert
        # agent._suggest_category.assert_called_once_with("General Question", TicketCategory.GENERAL.value)
        # agent._suggest_priority.assert_called_once_with("General Question", None)
